METRIC_LABELS = {
    "off_epa": "Offensive EPA / play",
    "def_epa": "Defensive EPA / play",
    "pass_epa": "Pass EPA / play",
    "rush_epa": "Rush EPA / play",
    "success_rate": "Success rate",
    "pace": "Pace",
    "rest": "Rest",
    "record": "Record",
}

SAMPLE_GAMES = [
    {
        "week": 1,
        "day": "Thursday",
        "time": "8:20 PM ET",
        "away": {
            "name": "Dallas Cowboys",
            "abbr": "DAL",
            "win_prob": 0.39,
            "metrics": {
                "off_epa": 0.061,
                "def_epa": 0.018,
                "pass_epa": 0.094,
                "rush_epa": 0.012,
                "success_rate": 0.446,
                "pace": 64.2,
                "rest": 7,
                "record": "0-0",
            },
        },
        "home": {
            "name": "Philadelphia Eagles",
            "abbr": "PHI",
            "win_prob": 0.61,
            "metrics": {
                "off_epa": 0.142,
                "def_epa": 0.081,
                "pass_epa": 0.168,
                "rush_epa": 0.101,
                "success_rate": 0.491,
                "pace": 66.8,
                "rest": 7,
                "record": "0-0",
            },
        },
    },
    {
        "week": 1,
        "day": "Sunday",
        "time": "1:00 PM ET",
        "away": {
            "name": "Buffalo Bills",
            "abbr": "BUF",
            "win_prob": 0.67,
            "metrics": {
                "off_epa": 0.176,
                "def_epa": 0.096,
                "pass_epa": 0.221,
                "rush_epa": 0.071,
                "success_rate": 0.502,
                "pace": 66.1,
                "rest": 7,
                "record": "0-0",
            },
        },
        "home": {
            "name": "Miami Dolphins",
            "abbr": "MIA",
            "win_prob": 0.33,
            "metrics": {
                "off_epa": 0.071,
                "def_epa": -0.014,
                "pass_epa": 0.097,
                "rush_epa": 0.029,
                "success_rate": 0.437,
                "pace": 63.7,
                "rest": 7,
                "record": "0-0",
            },
        },
    },
    {
        "week": 1,
        "day": "Sunday",
        "time": "4:25 PM ET",
        "away": {
            "name": "Minnesota Vikings",
            "abbr": "MIN",
            "win_prob": 0.46,
            "metrics": {
                "off_epa": 0.103,
                "def_epa": 0.067,
                "pass_epa": 0.131,
                "rush_epa": 0.054,
                "success_rate": 0.462,
                "pace": 64.8,
                "rest": 7,
                "record": "0-0",
            },
        },
        "home": {
            "name": "Detroit Lions",
            "abbr": "DET",
            "win_prob": 0.54,
            "metrics": {
                "off_epa": 0.159,
                "def_epa": 0.074,
                "pass_epa": 0.187,
                "rush_epa": 0.112,
                "success_rate": 0.487,
                "pace": 67.0,
                "rest": 7,
                "record": "0-0",
            },
        },
    },
    {
        "week": 2,
        "day": "Sunday",
        "time": "1:00 PM ET",
        "away": {
            "name": "Green Bay Packers",
            "abbr": "GB",
            "win_prob": 0.58,
            "metrics": {
                "off_epa": 0.128,
                "def_epa": 0.053,
                "pass_epa": 0.151,
                "rush_epa": 0.083,
                "success_rate": 0.476,
                "pace": 65.1,
                "rest": 7,
                "record": "1-0",
            },
        },
        "home": {
            "name": "Chicago Bears",
            "abbr": "CHI",
            "win_prob": 0.42,
            "metrics": {
                "off_epa": 0.057,
                "def_epa": 0.021,
                "pass_epa": 0.074,
                "rush_epa": 0.041,
                "success_rate": 0.441,
                "pace": 63.9,
                "rest": 7,
                "record": "0-1",
            },
        },
    },
]
